Improve non-alphanumeric character translation
Use a regular expression instead of string.translate to replace
non-alphanumeric characters with periods. This is more robust,
specifically when the version string is Unicode on Python 2.
This case currently causes the following error:

  TypeError: character mapping must return integer, None or unicode

It is also simpler to understand.